apiVersion: apps/v1
kind: Deployment
metadata:
  name: saran-flaskapp-deployment
  labels:
    app: flaskapp
spec:
  selector:
    matchLabels:
      app: flaskapp
  replicas: 3
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: kajasaran/kubesba:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: saran-flaskapp-service
spec:
  type: NodePort
  selector:
    app: flaskapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
